# Generated by Django 3.1.5 on 2021-02-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of book')),
                ('description', models.TextField(blank=True, null=True, verbose_name="book's description")),
            ],
        ),
    ]
