# Generated by Django 3.1.5 on 2021-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='autors of book'),
        ),
    ]
